from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

olcham = KeyboardButton("O'lchamlarni olish")
malumot = KeyboardButton("Ma'lumotlarni kiritish")
shift = KeyboardButton("O'lchamlarni kiritish")
button2 = KeyboardButton("Tugatish")
boshBtn = KeyboardButton("Bosh sahifa")
ostenBtn1 = KeyboardButton("Shahta o'lchamlarini olish")
ostenBtn2 = KeyboardButton("Obramleniya o'lchamlarini olish")
ostenBtn3 = KeyboardButton("Birnima")
telefonBtn = KeyboardButton("Mening telefon raqamim", request_contact=True)
adressBtn = KeyboardButton("Joylashuvni yuborish", request_location=True)

# inline
sana = InlineKeyboardButton(text="Bugungi sana", callback_data='sana')
toxtatishBtn = InlineKeyboardButton(text="To'xtatish", callback_data='stop')
keyingi = InlineKeyboardButton(text="Davom ettirish", callback_data='next')
daBtn = InlineKeyboardButton(text="Bor", callback_data='da')
netBtn = InlineKeyboardButton(text="Yo'q", callback_data='net')
beton = InlineKeyboardButton(text="Beton", callback_data='beton')
gisht = InlineKeyboardButton(text="G'isht", callback_data='gisht')
metal = InlineKeyboardButton(text="Metal konstruksiya", callback_data='metal')
none = InlineKeyboardButton(text="Devor yo'q", callback_data="yoq")

osten = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(olcham)
osten2 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(malumot)
osten3 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(shift)
keyboard2 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(button2)
Bosh_sahifa = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(boshBtn)
menu = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(ostenBtn1).add(ostenBtn2).add(ostenBtn3)
telefon = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(telefonBtn)
osten2Toxtatish = InlineKeyboardMarkup(row_width=1).add(toxtatishBtn, keyingi)
adress = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(adressBtn)
get_data = InlineKeyboardMarkup(row_width=1).add(sana)
daNet = InlineKeyboardMarkup().add(daBtn, netBtn)
devor_tur = InlineKeyboardMarkup().add(beton, gisht).add(metal)
old_devor_tur = InlineKeyboardMarkup().add(beton, gisht).add(metal, none)
