from aiogram.dispatcher.filters.state import State, StatesGroup

class Form(StatesGroup):
    loyiha_nomi = State()
    sana = State()
    menedjer = State()
    shahta_turi = State()
    mrlOrRl = State()
    olcham = State()
    qavat = State()
    eshiklar_soni = State()
    P = State()
    Hp = State()
    Eslatma = State()

class Form2(StatesGroup):
    loyiha_nomi = State()
    adres = State()
    injiner = State()
    montajnik = State()
    telefon = State()
    data = State()
    eshik = State()
    kenglik = State()
    qavat = State()

class Form3(StatesGroup):
    loyiha_nomi = State()
    qavat = State()
    mejdu = State()
    steni = State()
    priyamka = State()
    visota = State()
    stenki = State()
    plashad_pod = State()
    orqa = State()
    chap_yon = State()
    ong_yon = State()
    old_chap = State()
    old_ong = State()
    beton = State()
    mashina = State()
    eslatma = State()
    podgatovil = State()
    data = State()